name: TEST artifacts

on:
  workflow_dispatch:
  push:

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      HELM_SECRETS_WINDOWS_SHELL: ${{ matrix.shell == 'wsl' && 'wsl' || 'bash' }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        container: [""]
        shell: [dash]
        jobs: [4]
        include:
          - os: windows-latest
            shell: cygwin
            jobs: 1
    steps:
      - name: Install dependencies
        if: "matrix.container"
        run: |-
          if command -v apk > /dev/null; then
            apk add --no-cache curl
          elif command -v apt-get > /dev/null; then
            apt-get update -qqy
            apt-get install -qqy curl
          fi


      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: gnupg2,perl
      - run: |
          which curl
          which wget
          ls -lah /usr/bin/
          curl -sSfLJo /usr/bin/parallel http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
          chmod +x /usr/bin/parallel
          parallel --help
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -o pipefail -o igncr '{0}'
